<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | Travel Calculator</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						background-color: #f4f7f6;
						margin: 0;
						padding: 40px;
					}
					h1 { color: #2c3e50; font-size: 24px; margin-bottom: 20px; }
					p { color: #666; font-size: 14px; line-height: 1.6; }
					table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
					th { background-color: #3498db; color: #fff; text-align: left; padding: 12px 15px; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
					td { padding: 12px 15px; border-bottom: 1px solid #edf2f7; font-size: 14px; }
					tr:last-child td { border-bottom: none; }
					tr:hover td { background-color: #f8fafc; }
					a { color: #3498db; text-decoration: none; font-weight: 500; }
					a:hover { text-decoration: underline; }
					.priority { font-weight: bold; color: #27ae60; }
				</style>
			</head>
			<body>
				<h1>XML Sitemap</h1>
				<p>This sitemap is generated by Travel Calculator to help search engines like Google discover and index our programmatic pages.</p>
				<table>
					<thead>
						<tr>
							<th width="70%">URL</th>
							<th width="15%">Priority</th>
							<th width="15%">Last Mod</th>
						</tr>
					</thead>
					<tbody>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<tr>
								<td>
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
								</td>
								<td><span class="priority"><xsl:value-of select="sitemap:priority"/></span></td>
								<td><xsl:value-of select="sitemap:lastmod"/></td>
							</tr>
						</xsl:for-each>
						<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
							<tr>
								<td>
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<a href="{$itemURL}">Sub-sitemap: <xsl:value-of select="sitemap:loc"/></a>
								</td>
								<td>Index</td>
								<td>-</td>
							</tr>
						</xsl:for-each>
					</tbody>
				</table>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
